spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

management:
  endpoints:
    web:
      exposure:
        include: env

#flyway:
#  url: ${spring.datasource.url}
#  user: ${spring.datasource.username}
#  password: ${spring.datasource.password}