spring:
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: env

#flyway:
#  url: ${spring.datasource.url}
#  user: ${spring.datasource.username}
#  password: ${spring.datasource.password}